#Michael Kitzan
#CS 140
#File Name: MichaelKitzanTicTacToe.py
#Explaination: Program runs a functional Tic Tac Toe game
#Meant to be played in a cmd console window

# This is the main data structure we will be working with. It is an array
# containing three arrays. Each of the contained arrays is an array with
# three positions. Each position is initialized to a blank space, ' '.
from random import *
from os import *

def printBoard(playBoard):
    """This function will print out the contents of the variable passed
    into the function by the name of board."""
    print("")
    print("    0     1     2")
    print("       |     |     ")
    print(" 0 ", playBoard[0][0], " | ", playBoard[0][1], " | ", playBoard[0][2])
    print("       |     |     ")
    print("  -----+-----+-----")
    print("       |     |     ")
    print(" 1 ", playBoard[1][0], " | ", playBoard[1][1], " | ", playBoard[1][2])
    print("       |     |     ")
    print("  -----+-----+-----")
    print("       |     |     ")
    print(" 2 ", playBoard[2][0], " | ", playBoard[2][1], " | ", playBoard[2][2])
    print("       |     |     ")
    print("")
    return
  
def isValidMove(playBoard, coordX, coordY):
    """Takes in an x and y value are returns a boolean reporting True or False
    if a piece can be placed in the location or not."""
    if coordX not in range(0, 3):
        invalidMove(playBoard)
    if coordY not in range(0, 3):
        invalidMove(playBoard)
    if playBoard[coordX][coordY] == ' ':
        return True
    else:
        return False

def playerMove(playBoard):
    """Will contain the necessary logic to execute a players move."""
    print(" Enter your move")
    try:
        y = int(input(" Column: "))
    except ValueError:
        invalidMove(playBoard)
    try:
        x = int(input(" Row: "))
    except ValueError:
        invalidMove(playBoard)
    if isValidMove(playBoard, x, y) == True:
        playBoard[x][y] = 'X'
        testWin(playBoard, 1)
    else:
        invalidMove(playBoard)

def invalidMove(playBoard):
    """Returns program back to player move. Only here to reduce repeat code"""
    system('cls')
    printBoard(playBoard)
    print(' Move invalid, retry')
    playerMove(playBoard)

def computerMove(playBoard):
    """Will contain the necessary logic to execute the computers move."""
    numberSelection = [0, 1, 2, 0, 1, 2]
    shuffle(numberSelection)
    x = numberSelection[0]
    y = numberSelection[1]
    if isValidMove(playBoard, x, y) == True:
        playBoard[x][y] = 'O'
        testWin(playBoard, 2)
    else:
        computerMove(playBoard)
    #Is it efficient, no, but it works

def testWin(playBoard, call):
    """Recommended to call this function after every piece has been placed.
    Will let us know if the person or computer has won the game."""
    system('cls')
    test = False
    if playBoard[1][1] != ' ':
        if playBoard[0][0] == playBoard[1][1] == playBoard[2][2]:
            test = True
        if playBoard[0][2] == playBoard[1][1] == playBoard[2][0]:
            test = True
        if playBoard[1][0] == playBoard[1][1] == playBoard[1][2]:
            test = True
        if playBoard[0][1] == playBoard[1][1] == playBoard[2][1]:
            test = True
    if playBoard[0][0] != ' ':
        if playBoard[0][0] == playBoard[0][1] == playBoard[0][2]:
            test = True
        if playBoard[0][0] == playBoard[1][0] == playBoard[2][0]:
            test = True
    if playBoard[2][2] != ' ':
        if playBoard[0][2] == playBoard[1][2] == playBoard[2][2]:
            test = True
        if playBoard[2][0] == playBoard[2][1] == playBoard[2][2]:
            test = True
    if test == True:
        printBoard(playBoard)
        if call == 1:
            print(" You win")
            print(" Play again? Yes or No")
            answer = input(" ")
            answer = answer[:3].upper()
            if answer == ("YES"):
                main()
            if answer == ("NO"):
                exit()
            else:
                testWin(playBoard, call)
        else:
            print(" You lost")
            print(" Play again? Yes or No")
            answer = input(" ")
            answer = answer[:3].upper()
            if answer == ("YES"):
                main()
            if answer == ("NO"):
                exit()
            else:
                testWin(playBoard, call)
    else:
        fullBoard(playBoard, call)
    #I had a more efficeint version using for and while loops, but it was way too buggy

def fullBoard(playBoard, call):
    """Returns a boolean value reporting the state of the board, full or not.
    True for full, False for not full."""
    i = 0
    j = 0
    #I was running into errors when running the program without the intialization before the loop
    for i in range(len(playBoard)):
      for j in range(len(playBoard)):
        if i == 2 and j == 2:
          if playBoard[i][j] != ' ':
            printBoard(playBoard)
            print(" The board is full")
            print(" Play again? Yes or No")
            answer = input(" ")
            answer = answer[:3].upper()
            if answer == ("YES"):
                main()
            if answer == ("NO"):
                exit()
            else:
                fullBoard(playBoard, call)
        elif playBoard[i][j] == ' ':
          if call == 1:
            computerMove(playBoard)
          else:
            playGame(playBoard)

def playGame(playBoard):
    """This is the main function that will contain the logic and other function
    calls. It will stitch together the other logic in the other functions to
    create a working Tic Tac Toe game."""
    printBoard(playBoard)
    playerMove(playBoard)

def main():
    """Front end of the program"""
    system('cls')
    playBoard = [[' ' for x in range(3)] for y in range(3)]
    playGame(playBoard)
    #End of the core of the program except for the 'main' call, and setting the title

def title():
    """Title screen with multiple starting animations"""
    if randint(0,1) == 0:
        system('cls')
        print(" ##############################")
        print("#  _______   _______   ______  #")
        print("# |__   __| |__   __| |  ____| #")
        print("#    | |       | |    | |      #")
        print("#    | |       | |    | |      #")
        print("#    | |     __| |__  | |____  #")
        print("#    |_|    |_______| |______| #")
        print("#  _______   _______   ______  #")
        print("# |__   __| |  ___  | |  ____| #")
        print("#    | |    | |___| | | |      #")
        print("#    | |    |  ___  | | |      #")
        print("#    | |    | |   | | | |____  #")
        print("#    |_|    |_|   |_| |______| #")
        print("#  _______   _______   ______  #")
        print("# |__   __| |  ___  | |  ____| #")
        print("#    | |    | |   | | | |___   #")
        print("#    | |    | |   | | |  ___|  #")
        print("#    | |    | |___| | | |____  #")
        print("#    |_|    |_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        input()
        system('cls')
        print(" ##############################")
        print("#   _______  _______  ______   #")
        print("#  |__   __||__   __||  ____|  #")
        print("#     | |      | |   | |       #")
        print("#     | |      | |   | |       #")
        print("#     | |    __| |__ | |____   #")
        print("#     |_|   |_______||______|  #")
        print("#   _______  _______  ______   #")
        print("#  |__   __||  ___  ||  ____|  #")
        print("#     | |   | |___| || |       #")
        print("#     | |   |  ___  || |       #")
        print("#     | |   | |   | || |____   #")
        print("#     |_|   |_|   |_||______|  #")
        print("#   _______  _______  ______   #")
        print("#  |__   __||  ___  ||  ____|  #")
        print("#     | |   | |   | || |___    #")
        print("#     | |   | |   | ||  ___|   #")
        print("#     | |   | |___| || |____   #")
        print("#     |_|   |_______||______|  #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#    _______ _______ ______    #")
        print("#   |__   __|__   __|  ____|   #")
        print("#      | |     | |  | |        #")
        print("#      | |     | |  | |        #")
        print("#      | |   __| |__| |____    #")
        print("#      |_|  |_______|______|   #")
        print("#    _______ _______ ______    #")
        print("#   |__   __|  ___  |  ____|   #")
        print("#      | |  | |___| | |        #")
        print("#      | |  |  ___  | |        #")
        print("#      | |  | |   | | |____    #")
        print("#      |_|  |_|   |_|______|   #")
        print("#    _______ _______ ______    #")
        print("#   |__   __|  ___  |  ____|   #")
        print("#      | |  | |   | | |___     #")
        print("#      | |  | |   | |  ___|    #")
        print("#      | |  | |___| | |____    #")
        print("#      |_|  |_______|______|   #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#     ____________________     #")
        print("#    |__   ____   _   ____|    #")
        print("#       | |    | | | |         #")
        print("#       | |    | | | |         #")
        print("#       | |  __| |_| |____     #")
        print("#       |_| |_____________|    #")
        print("#     ____________________     #")
        print("#    |__   _   ___    ____|    #")
        print("#       | | | |___|  |         #")
        print("#       | | |  ___   |         #")
        print("#       | | | |   |  |____     #")
        print("#       |_| |_|   |_______|    #")
        print("#     ____________________     #")
        print("#    |__   _   ___    ____|    #")
        print("#       | | | |   |  |___      #")
        print("#       | | | |   |   ___|     #")
        print("#       | | | |___|  |____     #")
        print("#       |_| |_____________|    #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#      __________________      #")
        print("#     |__   ___      ____|     #")
        print("#        | |   | || |          #")
        print("#        | |   | || |          #")
        print("#        | | __| || |____      #")
        print("#        |_||____________|     #")
        print("#      __________________      #")
        print("#     |__      ___   ____|     #")
        print("#        | || |___| |          #")
        print("#        | ||  ___  |          #")
        print("#        | || |   | |____      #")
        print("#        |_||_|   |______|     #")
        print("#      __________________      #")
        print("#     |__      ___   ____|     #")
        print("#        | || |   | |___       #")
        print("#        | || |   |  ___|      #")
        print("#        | || |___| |____      #")
        print("#        |_||____________|     #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#       ________________       #")
        print("#      |__   __     ____|      #")
        print("#         | |  | | |           #")
        print("#         | |  | | |           #")
        print("#         | |__| | |____       #")
        print("#         |_____________|      #")
        print("#       ________________       #")
        print("#      |__     __   ____|      #")
        print("#         | | |__| |           #")
        print("#         | |  __  |           #")
        print("#         | | |  | |____       #")
        print("#         |_|_|  |______|      #")
        print("#       ________________       #")
        print("#      |__     __   ____|      #")
        print("#         | | |  | |___        #")
        print("#         | | |  |  ___|       #")
        print("#         | | |__| |____       #")
        print("#         |_|___________|      #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#        ______________        #")
        print("#       |__   _    ____|       #")
        print("#          | | |  |            #")
        print("#          | | |  |            #")
        print("#          | |_|  |____        #")
        print("#          |___________|       #")
        print("#        ______________        #")
        print("#       |__    _   ____|       #")
        print("#          |  |_| |            #")
        print("#          |   _  |            #")
        print("#          |  | | |____        #")
        print("#          |__| |______|       #")
        print("#        ______________        #")
        print("#       |__    _   ____|       #")
        print("#          |  | | |___         #")
        print("#          |  | |  ___|        #")
        print("#          |  |_| |____        #")
        print("#          |___________|       #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#         ____________         #")
        print("#        |__      ____|        #")
        print("#           | || |             #")
        print("#           | || |             #")
        print("#           | || |____         #")
        print("#           |_________|        #")
        print("#         ____________         #")
        print("#        |__      ____|        #")
        print("#           | || |             #")
        print("#           | || |             #")
        print("#           | || |____         #")
        print("#           |_||______|        #")
        print("#         ____________         #")
        print("#        |__      ____|        #")
        print("#           | || |___          #")
        print("#           | ||  ___|         #")
        print("#           | || |____         #")
        print("#           |_________|        #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#          __________          #")
        print("#         |__    ____|         #")
        print("#            |  |              #")
        print("#            |  |              #")
        print("#            |  |____          #")
        print("#            |_______|         #")
        print("#          __________          #")
        print("#         |__    ____|         #")
        print("#            |  |              #")
        print("#            |  |              #")
        print("#            |  |____          #")
        print("#            |_______|         #")
        print("#          __________          #")
        print("#         |__    ____|         #")
        print("#            |  |___           #")
        print("#            |   ___|          #")
        print("#            |  |____          #")
        print("#            |_______|         #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#           ________           #")
        print("#          |__   ___|          #")
        print("#             | |              #")
        print("#             | |              #")
        print("#             | |___           #")
        print("#             |_____|          #")
        print("#           ________           #")
        print("#          |__   ___|          #")
        print("#             | |              #")
        print("#             | |              #")
        print("#             | |___           #")
        print("#             |_____|          #")
        print("#           ________           #")
        print("#          |__   ___|          #")
        print("#             | |__            #")
        print("#             |  __|           #")
        print("#             | |___           #")
        print("#             |_____|          #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |_            #")
        print("#              |___|           #")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |_            #")
        print("#              |___|           #")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |_            #")
        print("#              |___|           #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              |_|             #")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              |_|             #")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              |_|             #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        input()
    else:
        system('cls')
        print(" ##############################")
        print("#  _______   _______   ______  #")
        print("# |__   __| |__   __| |  ____| #")
        print("#    | |       | |    | |      #")
        print("#    | |       | |    | |      #")
        print("#    | |     __| |__  | |____  #")
        print("#    |_|    |_______| |______| #")
        print("#  _______   _______   ______  #")
        print("# |__   __| |  ___  | |  ____| #")
        print("#    | |    | |___| | | |      #")
        print("#    | |    |  ___  | | |      #")
        print("#    | |    | |   | | | |____  #")
        print("#    |_|    |_|   |_| |______| #")
        print("#  _______   _______   ______  #")
        print("# |__   __| |  ___  | |  ____| #")
        print("#    | |    | |   | | | |___   #")
        print("#    | |    | |   | | |  ___|  #")
        print("#    | |    | |___| | | |____  #")
        print("#    |_|    |_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        input()
        system('cls')
        print(" ##############################")
        print("#  _______ _______   ______    #")
        print("# |__   __|__   __| |  ____|   #")
        print("#    | |     | |    | |        #")
        print("#    | |     | |    | |        #")
        print("#    | |   __| |__  | |____    #")
        print("#    |_|  |_______| |______|   #")
        print("#   _______  _______   ______  #")
        print("#  |__   __||  ___  | |  ____| #")
        print("#     | |   | |___| | | |      #")
        print("#     | |   |  ___  | | |      #")
        print("#     | |   | |   | | | |____  #")
        print("#     |_|   |_|   |_| |______| #")
        print("#    _______ _______   ______  #")
        print("#   |__   __|  ___  | |  ____| #")
        print("#      | |  | |   | | | |___   #")
        print("#      | |  | |   | | |  ___|  #")
        print("#      | |  | |___| | | |____  #")
        print("#      |_|  |_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _____________   ______      #")
        print("# |__   ___   __| |  ____|     #")
        print("#    | |   | |    | |          #")
        print("#    | |   | |    | |          #")
        print("#    | | __| |__  | |____      #")
        print("#    |_||_______| |______|     #")
        print("#    _______ _______   ______  #")
        print("#   |__   __|  ___  | |  ____| #")
        print("#      | |  | |___| | | |      #")
        print("#      | |  |  ___  | | |      #")
        print("#      | |  | |   | | | |____  #")
        print("#      |_|  |_|   |_| |______| #")
        print("#      _____________   ______  #")
        print("#     |__      ___  | |  ____| #")
        print("#        | || |   | | | |___   #")
        print("#        | || |   | | |  ___|  #")
        print("#        | || |___| | | |____  #")
        print("#        |_||_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  ___________   ______        #")
        print("# |__   _   __| |  ____|       #")
        print("#    | | | |    | |            #")
        print("#    | | | |    | |            #")
        print("#    | |_| |__  | |____        #")
        print("#    |_|______| |______|       #")
        print("#     ______________   ______  #")
        print("#    |__   _   ___  | |  ____| #")
        print("#       | | | |___| | | |      #")
        print("#       | | |  ___  | | |      #")
        print("#       | | | |   | | | |____  #")
        print("#       |_| |_|   |_| |______| #")
        print("#      _____________   ______  #")
        print("#     |__      ___  | |  ____| #")
        print("#        | || |   | | | |___   #")
        print("#        | || |   | | |  ___|  #")
        print("#        | || |___| | | |____  #")
        print("#        |_||_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _________   ______          #")
        print("# |__     __| |  ____|         #")
        print("#    | | |    | |              #")
        print("#    | | |    | |              #")
        print("#    | | |__  | |____          #")
        print("#    |______| |______|         #")
        print("#      _____________   ______  #")
        print("#     |__      ___  | |  ____| #")
        print("#        | || |___| | | |      #")
        print("#        | ||  ___  | | |      #")
        print("#        | || |   | | | |____  #")
        print("#        |_||_|   |_| |______| #")
        print("#        ___________   ______  #")
        print("#       |__    ___  | |  ____| #")
        print("#          |  |   | | | |___   #")
        print("#          |  |   | | |  ___|  #")
        print("#          |  |___| | | |____  #")
        print("#          |________| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _______   ______            #")
        print("# |__   __| |  ____|           #")
        print("#    | |    | |                #")
        print("#    | |    | |                #")
        print("#    | |__  | |____            #")
        print("#    |____| |______|           #")
        print("#       ____________   ______  #")
        print("#      |__     ___  | |  ____| #")
        print("#         | | |___| | | |      #")
        print("#         | |  ___  | | |      #")
        print("#         | | |   | | | |____  #")
        print("#         |_|_|   |_| |______| #")
        print("#         __________   ______  #")
        print("#        |__   ___  | |  ____| #")
        print("#           | |   | | | |___   #")
        print("#           | |   | | |  ___|  #")
        print("#           | |___| | | |____  #")
        print("#           |_______| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _______ ______              #")
        print("# |__   __|  ____|             #")
        print("#    | |  | |                  #")
        print("#    | |  | |                  #")
        print("#    | |  | |____              #")
        print("#    |_|  |______|             #")
        print("#        ___________   ______  #")
        print("#       |__    ___  | |  ____| #")
        print("#          |  |___| | | |      #")
        print("#          |   ___  | | |      #")
        print("#          |  |   | | | |____  #")
        print("#          |__|   |_| |______| #")
        print("#           ________   ______  #")
        print("#          |__   _  | |  ____| #")
        print("#             | | | | | |___   #")
        print("#             | | | | |  ___|  #")
        print("#             | |_| | | |____  #")
        print("#             |_____| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  ____________                #")
        print("# |__      ____|               #")
        print("#    | || |                    #")
        print("#    | || |                    #")
        print("#    | || |____                #")
        print("#    |_||______|               #")
        print("#          _________   ______  #")
        print("#         |__   __  | |  ____| #")
        print("#            | |__| | | |      #")
        print("#            |  __  | | |      #")
        print("#            | |  | | | |____  #")
        print("#            |_|  |_| |______| #")
        print("#             _______  ______  #")
        print("#            |__     ||  ____| #")
        print("#               | | | | |___   #")
        print("#               | | | |  ___|  #")
        print("#               | | | | |____  #")
        print("#               |___| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  __________                  #")
        print("# |__    ____|                 #")
        print("#    |  |                      #")
        print("#    |  |                      #")
        print("#    |  |____                  #")
        print("#    |_______|                 #")
        print("#           ________   ______  #")
        print("#          |__   _  | |  ____| #")
        print("#             | |_| | | |      #")
        print("#             |  _  | | |      #")
        print("#             | | | | | |____  #")
        print("#             |_| |_| |______| #")
        print("#               _____________  #")
        print("#              |__   _   ____| #")
        print("#                 | | | |___   #")
        print("#                 | | |  ___|  #")
        print("#                 | | | |____  #")
        print("#                 |_| |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  ________                    #")
        print("# |__   ___|                   #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    | |___                    #")
        print("#    |_____|                   #")
        print("#            _______   ______  #")
        print("#           |__     | |  ____| #")
        print("#              | || | | |      #")
        print("#              |    | | |      #")
        print("#              | || | | |____  #")
        print("#              |_||_| |______| #")
        print("#                 ___________  #")
        print("#                |__     ____| #")
        print("#                   | | |___   #")
        print("#                   | |  ___|  #")
        print("#                   | | |____  #")
        print("#                   |_|______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _______                     #")
        print("# |__   __|                    #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    |_|                       #")
        print("#            _______ ______    #")
        print("#           |__   __|  ____|   #")
        print("#              | |  | |        #")
        print("#              | |  | |        #")
        print("#              | |  | |____    #")
        print("#              |_|  |______|   #")
        print("#                   _________  #")
        print("#                  |__   ____| #")
        print("#                     | |___   #")
        print("#                     |  ___|  #")
        print("#                     | |____  #")
        print("#                     |______| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _______                     #")
        print("# |__   __|                    #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    |_|                       #")
        print("#            ____________      #")
        print("#           |__      ____|     #")
        print("#              | || |          #")
        print("#              | || |          #")
        print("#              | || |____      #")
        print("#              |_||______|     #")
        print("#                     _______  #")
        print("#                    |__   __| #")
        print("#                       | |_   #")
        print("#                       |  _|  #")
        print("#                       | |__  #")
        print("#                       |____| #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        system('cls')
        print(" ##############################")
        print("#  _______                     #")
        print("# |__   __|                    #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    |_|                       #")
        print("#            _________         #")
        print("#           |__   ____|        #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |___          #")
        print("#              |_____|         #")
        print("#                     _______  #")
        print("#                    |__   __| #")
        print("#                       | |    #")
        print("#                       | |    #")
        print("#                       | |    #")
        print("#                       |_|    #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        
        system('cls')
        print(" ##############################")
        print("#  _______                     #")
        print("# |__   __|                    #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    | |                       #")
        print("#    |_|                       #")
        print("#            _______           #")
        print("#           |__   __|          #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              | |             #")
        print("#              |_|             #")
        print("#                     _______  #")
        print("#                    |__   __| #")
        print("#                       | |    #")
        print("#                       | |    #")
        print("#                       | |    #")
        print("#                       |_|    #")
        print("#                              #")
        print("#       -MICHAEL KITZAN-       #")
        print(" ##############################")
        input()
    main()
    
system('title Tic Tac Toe')
title()
